=== quasar-team/quasar/Design/Design.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- Â© Copyright CERN, 2015.                                                       -->
<!-- All rights not expressly granted are reserved.                                -->
<!-- This file is part of Quasar.                                                  -->
<!--                                                                               -->
<!-- Quasar is free software: you can redistribute it and/or modify                -->     
<!-- it under the terms of the GNU Lesser General Public Licence as published by   -->     
<!-- the Free Software Foundation, either version 3 of the Licence.                -->     
<!-- Quasar is distributed in the hope that it will be useful,                     -->     
<!-- but WITHOUT ANY WARRANTY; without even the implied warranty of                -->     
<!--                                                                               -->
<!-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the                 -->
<!-- GNU Lesser General Public Licence for more details.                           -->
<!--                                                                               -->
<!-- You should have received a copy of the GNU Lesser General Public License      -->
<!-- along with Quasar.  If not, see <http://www.gnu.org/licenses/>                -->
<!--                                                                               -->
<!-- Created:   Jun 2014                                                           -->
<!-- Authors:                                                                      -->
<!--   Piotr Nikiel <piotr@nikiel.info>                                            -->

<schema xmlns="http://www.w3.org/2001/XMLSchema" 
targetNamespace="http://cern.ch/quasar/Design" 
xmlns:tns="http://cern.ch/quasar/Design" 
elementFormDefault="qualified">

    <complexType name="Design">
    	<sequence>
    		<element name="class" type="tns:Class" maxOccurs="unbounded"
    			minOccurs="0">

    			<!-- Restriction: uniqueness among names of cachevariable, sourcevariable, configentry -->
    			<key name="variableKey">
    				<selector
    					xpath="tns:cachevariable|tns:configentry|tns:sourcevariable" />
    				<field xpath="@name" />
    			</key>
    			<keyref name="__class__cachevariable__name__"
    				refer="tns:variableKey">
    				<selector xpath="tns:cachevariable" />
    				<field xpath="@name" />
    			</keyref>
    			<keyref name="__class__configentry__name__"
    				refer="tns:variableKey">
    				<selector xpath="tns:configentry" />
    				<field xpath="@name" />
    			</keyref>
    			<keyref name="__class__sourcevariable__name__"
    				refer="tns:variableKey">
    				<selector xpath="tns:sourcevariable" />
    				<field xpath="@name" />
    			</keyref>

    		</element>
    		<element name="root" type="tns:Root" maxOccurs="1"
    			minOccurs="1">
    		</element>
    	</sequence>
    	<attribute name="projectShortName" type="string"
    		use="required">
    	</attribute>

    	<attribute name="author" type="string"></attribute>
    </complexType>

    <element name="design" type="tns:Design">
    
    <!--  Restriction: no duplicate class names.  -->
    <key name="classKey">
    	<selector xpath="tns:class"/>
    	<field xpath="@name"></field>
    </key>
	<keyref name="__class__hasobjects__classkey__" refer="tns:classKey">
		<selector xpath="tns:class/tns:hasobjects" />
		<field xpath="@class" />
	</keyref>
	<keyref name="__root__hasobjects__classkey__" refer="tns:classKey">
		<selector xpath="tns:root/tns:hasobjects" />
		<field xpath="@class" />
	</keyref>
	
	
    </element>

    <complexType name="Class">
    	<sequence>
    		<element name="devicelogic" type="tns:DeviceLogic"
    			minOccurs="0" maxOccurs="1">
    		</element>
    		<sequence minOccurs="0" maxOccurs="unbounded">

    			<choice>
    				<element name="cachevariable"
    					type="tns:CacheVariable" />
    				<element name="sourcevariable"
    					type="tns:SourceVariable" />
    				<element name="method" type="tns:Method"></element>
    				<element name="hasobjects" type="tns:HasObjects" />
    				<element name="configentry" type="tns:ConfigEntry" />
    			</choice>
    		</sequence>
    	</sequence>


    	<attribute name="name" type="tns:ClassName" use="required"></attribute>
    	<attribute name="singleVariableNode" type="boolean" use="optional"></attribute>
    </complexType>

    <complexType name="CacheVariable">
    	<choice>
    		<element name="documentation" type="tns:Documentation" maxOccurs="1" minOccurs="0"></element>
    	</choice>
    	<attribute name="name" type="tns:VariableName" use="required"></attribute>
    	<attribute name="addressSpaceWrite"
    		type="tns:CacheVariableAddressSpaceWrite" use="required">
    		<annotation>
    		<documentation>
    		When "forbidden", any OPCUA write transaction will be denied with BadUserAccessDenied status.
    		When "regular", OPCUA write transactions matching chosen data type (or NULL if allowed) will be accepted and handled automatically.
    		When "delegated", OPCUA write transactions matching chosen data type (or NULL if allowed) will be first routed to the handler generated in Device Logic class, and stored in the cache only when the handler returns with Good status.
    		Note that choosing "forbidden" or "regular" doesn't generate any handler in the Device Logic class, but "delegated" does.
    		Note also that handler generated with "delegated" will be executed from the network thread, so it is not supposed to be blocking. For blocking handlers it is better to consider SourceVariable.
     		</documentation>
    		</annotation>
    	</attribute>
    	<attribute name="makeSetGet" type="boolean" use="optional">
      		<annotation>
    		<documentation>
    		This attribute is deprecated and will be removed soon.
     		</documentation>
    		</annotation>  	
    	</attribute>
    	<attribute name="dataType" type="tns:VariableDataType"
    		use="required">
    	</attribute>
    	<attribute name="initializeWith"
    		type="tns:VariableInitializeWith" use="required">
    	</attribute>
    	<attribute name="initialValue" type="string">
    	    <annotation>
    		<documentation>
    		Meaningful only when initializeWith="valueAndStatus". When this is the case, the value of this field specifies
    		initial value of this variable, i.e. 3.563 for floats or "ABCDE" for UaString or OpcUa_True for booleans.
    		Skipping this attribute will keep initialize this variable with NULL (provided that nullPolicy="nullAllowed").
     		</documentation>
    		</annotation>
    	</attribute>
    	<attribute name="initialStatus"
    		type="tns:VariableInitialStatus">
    		<annotation>
    		<documentation>
			Meaningful only when initializeWith="valueAndStatus", and then this is mandatory field.
     		</documentation>
    		</annotation>
    	</attribute>
    	<attribute name="isKey" type="boolean">
    		<annotation>
    		<documentation>
    		When "true", generates convenience functions for traversing device logic tree from Device Logic code.
    		I.e. when any children class' cachevariable has "isKey=true" then the parent class device logic will have function
    		getChildByVariable, assuming Child is the class name and Variable is the variable name.
    		</documentation>
    		</annotation>
    	</attribute>
    	<attribute name="nullPolicy" type="tns:NullPolicy" use="required">
    	    <annotation>
    		<documentation>
    		Sets whether NULL is accepted (applies to initialization, address space setters and write transactions by OPCUA client).
    		When "nullForbidden", no address space setter for NULL will be generated, and write transactions requesting storing NULL will be denied.
    		Note that when "nullAllowed" is chosen, compact address space getters will not be generated (i.e. double getValue()), and only long ones will exist (i.e. UaStatus getValue(double&amp; retval)).
     		</documentation>
    		</annotation>
    	</attribute>
    </complexType>

    <simpleType name="CacheVariableAddressSpaceWrite">
    	<restriction base="string">
    		<enumeration value="forbidden"></enumeration>
    		<enumeration value="delegated"></enumeration>
    		<enumeration value="regular"></enumeration>
    	</restriction>
    </simpleType>

    <complexType name="HasObjects">
    	<sequence>
    		<element name="object" type="tns:Object"
    			maxOccurs="unbounded" minOccurs="0">
    		</element>
    	</sequence>
    	<attribute name="class" type="string" use="required"></attribute>
    	<attribute name="instantiateUsing"
    		type="tns:HasObjectsInstantiatedUsing" use="required">
    	</attribute>
    	<attribute name="minOccurs" type="unsignedLong" use="optional"
    		default="0">
    	</attribute>
    	<attribute name="maxOccurs" type="unsignedLong" use="optional" default="4294967295"></attribute>
    </complexType>

    <simpleType name="VariableDataType">
    	<restriction base="string">
    		<enumeration value="OpcUa_Double"></enumeration>
    		<enumeration value="OpcUa_Float"></enumeration>
			<enumeration value="OpcUa_Byte"></enumeration>
    		<enumeration value="OpcUa_SByte"></enumeration>
			<enumeration value="OpcUa_Int16"></enumeration>
    		<enumeration value="OpcUa_UInt16"></enumeration>
    		<enumeration value="OpcUa_Int32"></enumeration>
    		<enumeration value="OpcUa_UInt32"></enumeration>
    		<enumeration value="OpcUa_Int64"></enumeration>
    		<enumeration value="OpcUa_UInt64"></enumeration>
    		<enumeration value="OpcUa_Boolean"></enumeration>
    		<enumeration value="UaString"></enumeration>
    		<enumeration value="UaVariant"></enumeration>
    		<enumeration value="UaByteString"></enumeration>
    	</restriction>
    </simpleType>

    <simpleType name="VariableInitializeWith">
    	<restriction base="string">
    		<enumeration value="configuration"></enumeration>
    		<enumeration value="valueAndStatus"></enumeration>
    	</restriction>
    </simpleType>

    <simpleType name="VariableName">
    	<restriction base="string">
    		<minLength value="1"></minLength>
    		<pattern value="[a-z]([A-Z]|[a-z]|\d|_)*"></pattern>
    	</restriction>
    </simpleType>

    <complexType name="Root">
    	<sequence>
    		<element name="hasobjects" type="tns:HasObjects" maxOccurs="unbounded" minOccurs="0"></element>
    	</sequence>
    </complexType>

    <simpleType name="VariableInitialStatus">
    	<restriction base="string">
    		<enumeration value="OpcUa_Good"></enumeration>
    		<enumeration value="OpcUa_Bad"></enumeration>
    		<enumeration value="OpcUa_BadWaitingForInitialData"></enumeration>
    	</restriction>
    </simpleType>

    <simpleType name="HasObjectsInstantiatedUsing">
    	<restriction base="string">
    		<enumeration value="configuration"></enumeration>
    		<enumeration value="design"></enumeration>
    	</restriction>
    </simpleType>

    <complexType name="Object">
    	<attribute name="name" type="string"></attribute>
    </complexType>

    <simpleType name="ClassName">
    	<restriction base="string">
    		<minLength value="1"></minLength>
    		<pattern value="[A-Z]([a-z]|[A-Z]|\d)*"></pattern>
    	</restriction>
    </simpleType>

    <complexType name="SourceVariable">
    	<attribute name="name" type="tns:VariableName" use="required"></attribute>
    	<attribute name="dataType" type="tns:VariableDataType"
    		use="required">
    	</attribute>
    	<attribute name="addressSpaceWrite" type="tns:SourceVariableAddressSpaceWrite" use="required">
 		 <annotation>
         <documentation>
         When "forbidden", any OPCUA write transaction will be denied with BadUserAccessDenied status.
         For "synchronous" and "asynchronous", OPCUA write transactions matching chosen data type (or NULL if allowed) will be routed to the handler generated in Device Logic class. 
         When "synchronous", the handler will be executed in the thread processing the request, so it must be non-blocking.
         When "asynchronous", the handler will be executed in a separate thread from the source variables thread pool.  
         </documentation>
         </annotation>
    	</attribute>
    	<attribute name="addressSpaceRead" type="tns:SourceVariableAddressSpaceRead" use="required">
    	<annotation>
         <documentation>
    	 When "forbidden", any OPCUA read transaction will be denied with BadUserAccessDenied status.
         For "synchronous" and "asynchronous", OPCUA read transactions will be routed to the handler generated in Device Logic class. 
         When "synchronous", the handler will be executed in the thread processing the request, so it must be non-blocking.
         When "asynchronous", the handler will be executed in a separate thread from the source variables thread pool.  
         </documentation>
         </annotation>
    	</attribute>
    	<attribute name="addressSpaceWriteUseMutex" type="tns:SourceVariableAddressSpaceOperationUseMutex" use="required">
    	<annotation>
        <documentation>
    	If different than "no", the lock of chosen object will be acquired before calling the handler, and released afterwards.
    	This is especially useful for "asynchronous" handler.
    	</documentation>
         </annotation> 
    	</attribute>
    	<attribute name="addressSpaceReadUseMutex" type="tns:SourceVariableAddressSpaceOperationUseMutex" use="required">
    	<annotation>
        <documentation>
        If different than "no", the lock of chosen object will be acquired before calling the handler, and released afterwards.
        This is especially useful for "asynchronous" handler.    	
        </documentation>
         </annotation>    	
    	</attribute>
    </complexType>

    <simpleType name="SourceVariableAddressSpaceWrite">
    	<restriction base="string">
    		<enumeration value="forbidden"></enumeration>
    		<enumeration value="asynchronous"></enumeration>
    		<enumeration value="synchronous"></enumeration>
    	</restriction>
    </simpleType>

    <simpleType name="SourceVariableAddressSpaceRead">
    	<restriction base="string">
    		<enumeration value="forbidden"></enumeration>
    		<enumeration value="asynchronous"></enumeration>
    		<enumeration value="synchronous"></enumeration>
    	</restriction>
    </simpleType>

    <simpleType name="SourceVariableAddressSpaceOperationUseMutex">
    	<restriction base="string">
    		<enumeration value="no"></enumeration>
    		<enumeration value="of_this_operation"></enumeration>
    		<enumeration value="of_this_variable"></enumeration>
    		<enumeration value="of_containing_object"></enumeration>
    		<enumeration value="of_parent_of_containing_object"></enumeration>
    	</restriction>
    </simpleType>
    
    <simpleType name="ConfigEntryDataType">
    <!--  this is essentially anything that variable data type might be apart from UaVariant -->
    	<restriction base="string">
    		<enumeration value="OpcUa_Double"></enumeration>
    		<enumeration value="OpcUa_Float"></enumeration>
			<enumeration value="OpcUa_Byte"></enumeration>
    		<enumeration value="OpcUa_SByte"></enumeration>
			<enumeration value="OpcUa_Int16"></enumeration>
    		<enumeration value="OpcUa_UInt16"></enumeration>
    		<enumeration value="OpcUa_Int32"></enumeration>
    		<enumeration value="OpcUa_UInt32"></enumeration>
    		<enumeration value="OpcUa_Int64"></enumeration>
    		<enumeration value="OpcUa_UInt64"></enumeration>
    		<enumeration value="OpcUa_Boolean"></enumeration>
    		<enumeration value="UaString"></enumeration>
    	</restriction>
    </simpleType>
    
    <complexType name="ConfigEntry">
    	<choice>
    		<element name="documentation" type="tns:Documentation"
    			maxOccurs="1" minOccurs="0">
    		</element>
    	</choice>
    	<attribute name="name" type="tns:VariableName" use="required"></attribute>
    	<attribute name="dataType" type="tns:ConfigEntryDataType"
    		use="required">
    	</attribute>
    	<attribute name="isKey" type="boolean"></attribute>
    	<attribute name="storedInDeviceObject" type="boolean" use="optional"></attribute>
    </complexType>

    <simpleType name="NullPolicy">
    	<restriction base="string">
    		<enumeration value="nullAllowed"></enumeration>
    		<enumeration value="nullForbidden"></enumeration>
    	</restriction>
    </simpleType>

    <simpleType name="Documentation">
    	<restriction base="string"></restriction>
    </simpleType>

    <complexType name="DeviceLogic">
    	<sequence>
    		<element name="mutex" type="tns:DeviceLogicMutex" minOccurs="0" maxOccurs="1"></element>
    	</sequence>
    </complexType>
    
    <complexType name="DeviceLogicMutex"></complexType>

    <complexType name="Method">
    	<sequence>
    		<element name="argument" type="tns:MethodArgument"
    			minOccurs="0" maxOccurs="unbounded">
    		</element>
    		<element name="returnvalue" type="tns:MethodReturnValue" minOccurs="0" maxOccurs="unbounded"></element>
    	</sequence>
    	<attribute name="name" type="tns:VariableName" use="required"></attribute>
    </complexType>
    
    <complexType name="MethodArgument">
    	<attribute name="name" type="tns:VariableName" use="required"></attribute>
    	<attribute name="dataType" type="tns:VariableDataType" use="required"></attribute>
    </complexType>

    <complexType name="MethodReturnValue">
    	<attribute name="dataType" type="tns:VariableDataType"
    		use="required">
    	</attribute>
    	<attribute name="name" type="tns:VariableName" use="required"></attribute>
    </complexType>
</schema>

=== quasar-team/quasar/Meta/design/meta-design.xml
<?xml version="1.0" encoding="UTF-8"?>
 <!-- 
Â© Copyright CERN, 2015.                                                    
All rights not expressly granted are reserved.                             
This file is part of Quasar.                                               
                                                                    
Quasar is free software: you can redistribute it and/or modify             
it under the terms of the GNU Lesser General Public Licence as published by
the Free Software Foundation, either version 3 of the Licence.             
Quasar is distributed in the hope that it will be useful,                  
but WITHOUT ANY WARRANTY; without even the implied warranty of             
                                                                    
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the              
GNU Lesser General Public Licence for more details.                        
                                                                    
You should have received a copy of the GNU Lesser General Public License   
along with Quasar.  If not, see <http://www.gnu.org/licenses/>             
                                                                    
Created:   July 2022                              
Authors:                                                                   
  Ben Farnham <ben.farnham@cern.ch>                                         
 -->

 <!-- 
File contains an XML snippet containing all classes used by the Meta module. the 
snippet is intended to be inserted into user's design.xml file (at build time) in
order that quasar generates the corresponding AS classes.

Note the requirement is that quasar generates the AddressSpace classes; Device 
class sources are provided (statically) in the Meta module.
 -->
<d:design projectShortName="OpcUaSampleServerNameChangeItInDesign" xmlns:d="http://cern.ch/quasar/Design" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://cern.ch/quasar/Design Design.xsd ">
    
  <d:class name="BuildInformation">
    <d:cachevariable name="BuildHost" addressSpaceWrite="forbidden" dataType="UaString" initializeWith="valueAndStatus" initialValue="UNKNOWN" initialStatus="OpcUa_BadWaitingForInitialData" nullPolicy="nullForbidden"/>
    <d:cachevariable name="BuildTimestamp" addressSpaceWrite="forbidden" dataType="UaString" initializeWith="valueAndStatus" initialValue="UNKNOWN" initialStatus="OpcUa_BadWaitingForInitialData" nullPolicy="nullForbidden"/>
    <d:cachevariable name="CommitID" addressSpaceWrite="forbidden" dataType="UaString" initializeWith="valueAndStatus" initialValue="UNKNOWN" initialStatus="OpcUa_BadWaitingForInitialData" nullPolicy="nullForbidden"/>
    <d:cachevariable name="ToolkitLibs" addressSpaceWrite="forbidden" dataType="UaString" initializeWith="valueAndStatus" initialValue="UNKNOWN" initialStatus="OpcUa_BadWaitingForInitialData" nullPolicy="nullForbidden"/>
  </d:class>
  
  <d:class name="LogLevel">
    <d:devicelogic/>
    <d:cachevariable name="logLevel" addressSpaceWrite="delegated" dataType="UaString" initializeWith="configuration" nullPolicy="nullForbidden"/>
  </d:class>
  
  <d:class name="ComponentLogLevels" defaultInstanceName="ComponentLogLevels">
    <d:hasobjects instantiateUsing="configuration" class="LogLevel" minOccurs="0"/>
  </d:class>
  
  <d:class name="Log" defaultInstanceName="Log">
    <d:hasobjects instantiateUsing="configuration" class="LogLevel" minOccurs="1" maxOccurs="1"/>
    <d:hasobjects class="ComponentLogLevels" instantiateUsing="configuration" minOccurs="1" maxOccurs="1"/>
  </d:class>
  
  <d:class name="Quasar">
    <d:cachevariable name="version" addressSpaceWrite="forbidden" dataType="UaString" initializeWith="valueAndStatus" initialValue="UNKNOWN" initialStatus="OpcUa_BadWaitingForInitialData" nullPolicy="nullForbidden"/>
  </d:class>
  
  <d:class name="Server">
    <d:cachevariable name="remainingCertificateValidity" addressSpaceWrite="forbidden" dataType="UaString" initializeWith="valueAndStatus" initialValue="UNKNOWN" initialStatus="OpcUa_BadWaitingForInitialData" nullPolicy="nullForbidden"/>
  </d:class>
  
  <d:class name="SourceVariableThreadPool" defaultInstanceName="SourceVariableThreadPool">
    <d:devicelogic/>
    <d:cachevariable name="maxThreads" addressSpaceWrite="forbidden" dataType="UaString" initializeWith="configuration" nullPolicy="nullForbidden"/>
    <d:cachevariable name="minThreads" addressSpaceWrite="forbidden" dataType="UaString" initializeWith="configuration" nullPolicy="nullForbidden"/>
  </d:class>
  
  <d:class name="StandardMetaData" defaultInstanceName="StandardMetaData">
    <d:hasobjects class="BuildInformation" instantiateUsing="design" minOccurs="1" maxOccurs="1">
      <d:object name="BuildInformation"/>
    </d:hasobjects>
    <d:hasobjects class="Log" instantiateUsing="configuration" minOccurs="1" maxOccurs="1"/>
    <d:hasobjects class="Quasar" instantiateUsing="design" minOccurs="1" maxOccurs="1">
      <d:object name="Quasar"/>
    </d:hasobjects>
    <d:hasobjects class="Server" instantiateUsing="design" minOccurs="1" maxOccurs="1">
      <d:object name="Server"/>
    </d:hasobjects>
    <d:hasobjects class="SourceVariableThreadPool" instantiateUsing="configuration" minOccurs="1" maxOccurs="1"/>
  </d:class>

  <d:root>
    <d:hasobjects class="StandardMetaData" instantiateUsing="configuration" minOccurs="1" maxOccurs="1">
      <d:object name="StandardMetaData"/>
    </d:hasobjects>
  </d:root>

</d:design>

=== quasar-team/quasar/.CI/test_cases/test_instantiation_from_design/Design.xml
<?xml version="1.0" encoding="UTF-8"?>
<d:design projectShortName="OpcUaSampleServerNameChangeItInDesign" xmlns:d="http://cern.ch/quasar/Design" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://cern.ch/quasar/Design Design.xsd ">

  <d:class name="DeviceInformation" defaultInstanceName="deviceInformation">
    <d:devicelogic/>
    <d:cachevariable name="status" dataType="OpcUa_Int32" addressSpaceWrite="forbidden" initializeWith="valueAndStatus" initialValue="0" initialStatus="OpcUa_BadWaitingForInitialData" nullPolicy="nullForbidden"/>
  </d:class>

  <d:class name="Controller" defaultInstanceName="controller">
    <d:devicelogic/>
    <d:hasobjects instantiateUsing="design" class="DeviceInformation" minOccurs="1" maxOccurs="1">
      <d:object name="deviceInformation"/>
    </d:hasobjects>
  </d:class>

  <d:class name="Rectifier">
    <d:hasobjects instantiateUsing="design" class="DeviceInformation" minOccurs="1" maxOccurs="1">
      <d:object name="deviceInformation"/>
    </d:hasobjects>
  </d:class>

  <d:class name="System" defaultInstanceName="system">
    <d:devicelogic/>
    <d:hasobjects instantiateUsing="design" class="Controller" minOccurs="1" maxOccurs="1">
      <d:object name="controller"/>
    </d:hasobjects>
    <d:hasobjects instantiateUsing="design" class="Rectifier" minOccurs="3" maxOccurs="3">
      <d:object name="rectifier1"/>
      <d:object name="rectifier2"/>
      <d:object name="rectifier3"/>
    </d:hasobjects>
    <d:hasobjects instantiateUsing="design" class="DeviceInformation" minOccurs="1" maxOccurs="1">
      <d:object name="deviceInformation"/>
    </d:hasobjects>
  </d:class>

  <d:root>
    <d:hasobjects instantiateUsing="design" class="System" minOccurs="1" maxOccurs="1">
      <d:object name="system"/>
    </d:hasobjects>
  </d:root>
</d:design>

=== quasar-team/quasar/.CI/test_cases/test_markdown_doc/Design.xml
<?xml version="1.0" encoding="UTF-8"?>
<d:design projectShortName="OpcUaSampleServerNameChangeItInDesign" xmlns:d="http://cern.ch/quasar/Design" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://cern.ch/quasar/Design Design.xsd ">
  <d:class name="ThisIsTheSingletonClass" defaultInstanceName="XX">


    <d:configentry dataType="UaString" name="dummy_configentry" storedInDeviceObject="true" >
      <d:documentation>
        Aliquam sit amet metus vel dui congue pulvinar id vel mauris. 
      </d:documentation>
    </d:configentry>


    <d:cachevariable dataType="OpcUa_Boolean" name="dummy_cv" initializeWith="configuration" addressSpaceWrite="regular" nullPolicy="nullAllowed">
      <d:documentation>
        Proin aliquam massa et arcu maximus, non efficitur dui gravida.
      </d:documentation>
    </d:cachevariable>

    <d:method name="dummy_method" executionSynchronicity="synchronous" addressSpaceCallUseMutex="no">
      <d:argument    dataType="OpcUa_Byte" name="byte_pulse">
        <d:documentation>
          Nunc eget ex gravida turpis varius venenatis a et dui. 
        </d:documentation>
      </d:argument>
      <d:documentation>
        Morbi pellentesque aliquam turpis eget finibus. Sed at lacinia arcu, at egestas velit. Mauris quis ligula commodo, tincidunt libero at, rutrum neque. Nunc rhoncus ultrices augue sed suscipit. Nullam ultricies vel massa sed rutrum. Quisque vitae odio sit amet felis rhoncus mollis porta viverra lacus. Curabitur molestie nisl quis mauris accumsan, id sagittis ex maximus. Aenean vitae lectus sed nisl fermentum pulvinar.  
      </d:documentation>
    </d:method>

    <d:documentation>
      Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis tincidunt eros ligula, in finibus ipsum suscipit at. Curabitur vel condimentum odio, ut luctus quam. Ut porttitor justo at rutrum eleifend. Aliquam et ex eleifend, dignissim magna et, dapibus magna. Donec id sem magna. Praesent sed dapibus lorem. Morbi vel pretium nulla. In tortor urna, dignissim vitae est vitae, condimentum ullamcorper dolor.
    </d:documentation>
  </d:class>

  <d:root>
    <d:hasobjects class="ThisIsTheSingletonClass" instantiateUsing="configuration" maxOccurs="1" minOccurs="1"/>
  </d:root>
</d:design>
